### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by shellscape** [egoist/vue-isomorphic-starter#11]
Got this after cloning and following the setup directions. You also seem to have a missing `babel-core` dep, as I had to install that manually.

```
ERROR in ./server/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/webpack-assets in /Users/powella/Code/github/vue-koa2/server
 @ ./server/index.js 35:21-55
/Users/powella/Code/github/vue-koa2/server.js:88
    var _webpackAssets = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../build/webpack-assets\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                                                   ^

Error: Cannot find module "../build/webpack-assets"
    at webpackMissingModule (/Users/powella/Code/github/vue-koa2/server.js:88:87)
    at Object.<anonymous> (/Users/powella/Code/github/vue-koa2/server.js:88:187)
    at __webpack_require__ (/Users/powella/Code/github/vue-koa2/server.js:20:30)
    at Object.<anonymous> (/Users/powella/Code/github/vue-koa2/server.js:47:19)
    at __webpack_require__ (/Users/powella/Code/github/vue-koa2/server.js:20:30)
    at /Users/powella/Code/github/vue-koa2/server.js:40:18
    at Object.<anonymous> (/Users/powella/Code/github/vue-koa2/server.js:43:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by APPLLEJN** [comment]
How to solve this？

**Comment by egoist** [comment]
Hmmm, this repo is kinda outdated, maybe you need https://github.com/vuejs/vue-hackernews-2.0 instead?

**Comment by APPLLEJN** [comment]
first npm run build and npm run dev?

**Comment by egoist** [comment]
@APPLLEJN yep, to start server it needs `webpack-assets.json` for the first run.
