### ISSUE TITLE
npm run dev can't find webpack-assets

### ISSUE THREAD

**Issue by rw3iss** [egoist/vue-isomorphic-starter#9]
ERROR in ./server/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/webpack-assets in /web/sites/vue-isomorphic-starter/server
 @ ./server/index.js 35:21-55
/web/sites/vue-isomorphic-starter/server.js:88
        var _webpackAssets = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../build/webpack-assets\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));

                                                             ^

Error: Cannot find module "../build/webpack-assets"
    at webpackMissingModule (/web/sites/vue-isomorphic-starter/server.js:88:87)
    at Object.<anonymous> (/web/sites/vue-isomorphic-starter/server.js:88:187)
    at __webpack_require__ (/web/sites/vue-isomorphic-starter/server.js:20:30)
    at Object.<anonymous> (/web/sites/vue-isomorphic-starter/server.js:47:19)
    at __webpack_require__ (/web/sites/vue-isomorphic-starter/server.js:20:30)
    at /web/sites/vue-isomorphic-starter/server.js:40:18
    at Object.<anonymous> (/web/sites/vue-isomorphic-starter/server.js:43:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
[nodemon] app crashed - waiting for file changes before starting...
ls

**Comment by rw3iss** [comment]
Had to run 'npm run build' first... also needed to change 'App.vue' to 'app.vue' in app.js.
